version: '3'

services:
  vault:
    hostname: vault
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id=root
    cap_add:
      - IPC_LOCK

  vault-init:
    container_name: vault-init
    image: hashicorp/vault:latest
    volumes:
      - ./vault-init.sh:/vault-init.sh
    depends_on:
      - vault
    restart: "no"
    entrypoint: sh -c "/vault-init.sh"

  sigstore-key-signer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigstore-key-signer
    stdin_open: true
    tty: true
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
